#ifndef PROTOCOL_CODES_H
#define PROTOCOL_CODES_H

#define IP_PROTOCOL_CODE              0x0008
#define ARP_PROTOCOL_CODE              0x0608
#define PPPOE_SESSION_PROTOCOL_CODE    0x6488

#endif // PROTOCOL_CODES_H
